### PR TITLE
Issue template

### PR DESCRIPTION
**Pull request by dabreadman**
## Purpose

It is painful to copy a paste the template from another issue, think about the user experience!  
image

## Proposed Change

Add templates for ***Issues*** and ***features***.

## Checklist

- [x] Issue request template
- [x] Feature request template
- [ ] Website request
- [x] Unnecessary anime memes
- [x] Unnecessary memes 

## Additional

- Added folder icon, because we like triangles.

### CODE REVIEW

**Comment by dabreadman** [comment]
**Blocking Issue**
No website request template.

**Reason**
We ain't got no website chief.

**Comment by lexesjan** [comment]
> **Blocking Issue** No website request template.
> 
> **Reason** We ain't got no website chief.

The website request is for adding new page support 😂 But yes, we should make a website sometime

**Comment by dabreadman** [comment]
> > **Blocking Issue** No website request template.
> > **Reason** We ain't got no website chief.
> 
> The website request is for adding new page support 😂 But yes, we should make a website sometime

Yeah, have to also figure out how to enable normal viewers to also contribute.
There's this extension [Visbug](https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc/related?hl=en), but `iframes` gonna be a hurdle.

**Comment by dabreadman** [comment]
> Yeah, have to also figure out how to enable normal viewers to also contribute. There's this extension [Visbug](https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc/related?hl=en), but `iframes` gonna be a hurdle.

Imagine forking it and adding ` all_frames: true`

**Review by lexesjan — COMMENTED** [review]
I realise that you've put a lot of effort into giving context and a description for each heading, but shouldn't these be comments (so that they don't appear in the actual issue submission)? Might be a pain to remove the template descriptions manually every time an issue is created.

**Review by lexesjan — APPROVED** [review]
LGTM!

**Pull request merged**
